In [1]:
pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 25.2 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 28.4 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [2]:
import pandas as pd

## Load Datasets

In [3]:
df_orders = pd.read_csv('/content/EcommiFyLab/olist_orders_dataset.csv')
display(df_orders.head())
display(df_orders.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

None

In [4]:
df_customers = pd.read_csv('/content/EcommiFyLab/olist_customers_dataset.csv')
display(df_customers.head())
display(df_customers.info())

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

None

In [5]:
df_order_items = pd.read_csv('/content/EcommiFyLab/olist_order_items_dataset.csv')
display(df_order_items.head())
display(df_order_items.info())

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

None

In [6]:
df_order_payments = pd.read_csv('/content/EcommiFyLab/olist_order_payments_dataset.csv')
display(df_order_payments.head())
display(df_order_payments.info())

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

None

In [7]:
df_order_reviews = pd.read_csv('/content/EcommiFyLab/olist_order_reviews_dataset.csv')
display(df_order_reviews.head())
display(df_order_reviews.info())

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

None

In [8]:
df_products = pd.read_csv('/content/EcommiFyLab/olist_products_dataset.csv')
display(df_products.head())
display(df_products.info())

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

None

In [9]:
df_sellers = pd.read_csv('/content/EcommiFyLab/olist_sellers_dataset.csv')
display(df_sellers.head())
display(df_sellers.info())

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

None

In [10]:
df_product_category_name_translation = pd.read_csv('/content/EcommiFyLab/product_category_name_translation.csv')
display(df_product_category_name_translation.head())
display(df_product_category_name_translation.info())

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

None

## Data Preprocessing

### Convert Timestamp Columns to Datetime

In [11]:
datetime_cols_orders = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
for col in datetime_cols_orders:
    df_orders[col] = pd.to_datetime(df_orders[col])
display(df_orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

None

In [12]:
df_order_items['shipping_limit_date'] = pd.to_datetime(df_order_items['shipping_limit_date'])
display(df_order_items.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

None

### Handle Missing Values

In [13]:
# For df_orders, fill missing `order_approved_at` with `order_purchase_timestamp`
df_orders['order_approved_at'] = df_orders['order_approved_at'].fillna(df_orders['order_purchase_timestamp'])

# For `order_delivered_carrier_date` and `order_delivered_customer_date`, fill missing values with `order_estimated_delivery_date`.
df_orders['order_delivered_carrier_date'] = df_orders['order_delivered_carrier_date'].fillna(df_orders['order_estimated_delivery_date'])
df_orders['order_delivered_customer_date'] = df_orders['order_delivered_customer_date'].fillna(df_orders['order_estimated_delivery_date'])

display(df_orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99441 non-null  datetime64[ns]
 5   order_delivered_carrier_date   99441 non-null  datetime64[ns]
 6   order_delivered_customer_date  99441 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

None

In [14]:
# For df_products
# Fill missing product_category_name with 'unknown'
df_products['product_category_name'] = df_products['product_category_name'].fillna('unknown')

# Fill numerical columns with their median
for col in ['product_name_lenght', 'product_description_lenght', 'product_photos_qty',
            'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']:
    df_products[col] = df_products[col].fillna(df_products[col].median())

display(df_products.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32951 non-null  object
 2   product_name_lenght         32951 non-null  float64
 3   product_description_lenght  32951 non-null  float64
 4   product_photos_qty          32951 non-null  float64
 5   product_weight_g            32951 non-null  float64
 6   product_length_cm           32951 non-null  float64
 7   product_height_cm           32951 non-null  float64
 8   product_width_cm            32951 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

None

In [15]:
# For df_order_reviews, fill missing comment titles and messages with empty strings
df_order_reviews['review_comment_title'] = df_order_reviews['review_comment_title'].fillna('')
df_order_reviews['review_comment_message'] = df_order_reviews['review_comment_message'].fillna('')

display(df_order_reviews.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  object
 4   review_comment_message   99224 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

None

### Merge Datasets

In [16]:
df_merged = pd.merge(df_orders, df_customers, on='customer_id', how='left')
display(df_merged.head())
display(df_merged.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99441 non-null  datetime64[ns]
 5   order_delivered_carrier_date   99441 non-null  datetime64[ns]
 6   order_delivered_customer_date  99441 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   customer_unique_id             99441 non-null  object
 9   customer_zip_code_prefix       99441 non-null  int64
 10  customer_city                  99441 non-null  object
 11  customer_state                 99441 non-null  object
dtypes: datetime64[ns](5), int64(1), object(6)
memory usage: 9.1+ MB

None

In [19]:
df_merged = pd.merge(df_merged, df_products, on='product_id', how='left')
display(df_merged.head())
display(df_merged.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  object
 1   customer_id                    113425 non-null  object
 2   order_status                   113425 non-null  object
 3   order_purchase_timestamp       113425 non-null  datetime64[ns]
 4   order_approved_at              113425 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113425 non-null  datetime64[ns]
 6   order_delivered_customer_date  113425 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113425 non-null  datetime64[ns]
 8   customer_unique_id             113425 non-null  object
 9   customer_zip_code_prefix       113425 non-null  int64
 10  customer_city                  113425 non-null  object
 11  customer_state                 113425 non-null  object
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  object
 14  seller_id                      112650 non-null  object
 15  shipping_limit_date            112650 non-null  datetime64[ns]
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  product_category_name          112650 non-null  object
 19  product_name_lenght            112650 non-null  float64
 20  product_description_lenght     112650 non-null  float64
 21  product_photos_qty             112650 non-null  float64
 22  product_weight_g               112650 non-null  float64
 23  product_length_cm              112650 non-null  float64
 24  product_height_cm              112650 non-null  float64
 25  product_width_cm               112650 non-null  float64
dtypes: datetime64[ns](6), float64(10), int64(1), object(9)
memory usage: 22.5+ MB

None

In [20]:
df_merged = pd.merge(df_merged, df_sellers, on='seller_id', how='left')
display(df_merged.head())
display(df_merged.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,59.0,468.0,3.0,450.0,30.0,10.0,20.0,31842.0,belo horizonte,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,38.0,316.0,4.0,250.0,51.0,15.0,15.0,8752.0,mogi das cruzes,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  object
 1   customer_id                    113425 non-null  object
 2   order_status                   113425 non-null  object
 3   order_purchase_timestamp       113425 non-null  datetime64[ns]
 4   order_approved_at              113425 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113425 non-null  datetime64[ns]
 6   order_delivered_customer_date  113425 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113425 non-null  datetime64[ns]
 8   customer_unique_id             113425 non-null  object
 9   customer_zip_code_prefix       113425 non-null  int64
 10  customer_city                  113425 non-null  object
 11  customer_state                 113425 non-null  object
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  object
 14  seller_id                      112650 non-null  object
 15  shipping_limit_date            112650 non-null  datetime64[ns]
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  product_category_name          112650 non-null  object
 19  product_name_lenght            112650 non-null  float64
 20  product_description_lenght     112650 non-null  float64
 21  product_photos_qty             112650 non-null  float64
 22  product_weight_g               112650 non-null  float64
 23  product_length_cm              112650 non-null  float64
 24  product_height_cm              112650 non-null  float64
 25  product_width_cm               112650 non-null  float64
 26  seller_zip_code_prefix         112650 non-null  float64
 27  seller_city                    112650 non-null  object
 28  seller_state                   112650 non-null  object
dtypes: datetime64[ns](6), float64(11), int64(1), object(11)
memory usage: 25.1+ MB

None

In [21]:
df_merged = pd.merge(df_merged, df_order_payments, on='order_id', how='left')
display(df_merged.head())
display(df_merged.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,19.0,8.0,13.0,9350.0,maua,SP,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,19.0,8.0,13.0,9350.0,maua,SP,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,19.0,8.0,13.0,9350.0,maua,SP,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,19.0,13.0,19.0,31570.0,belo horizonte,SP,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,24.0,19.0,21.0,14840.0,guariba,SP,1.0,credit_card,3.0,179.12

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118434 entries, 0 to 118433
Data columns (total 33 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118434 non-null  object
 1   customer_id                    118434 non-null  object
 2   order_status                   118434 non-null  object
 3   order_purchase_timestamp       118434 non-null  datetime64[ns]
 4   order_approved_at              118434 non-null  datetime64[ns]
 5   order_delivered_carrier_date   118434 non-null  datetime64[ns]
 6   order_delivered_customer_date  118434 non-null  datetime64[ns]
 7   order_estimated_delivery_date  118434 non-null  datetime64[ns]
 8   customer_unique_id             118434 non-null  object
 9   customer_zip_code_prefix       118434 non-null  int64
 10  customer_city                  118434 non-null  object
 11  customer_state                 118434 non-null  object
 12  order_item_id                  117604 non-null  float64
 13  product_id                     117604 non-null  object
 14  seller_id                      117604 non-null  object
 15  shipping_limit_date            117604 non-null  datetime64[ns]
 16  price                          117604 non-null  float64
 17  freight_value                  117604 non-null  float64
 18  product_category_name          117604 non-null  object
 19  product_name_lenght            117604 non-null  float64
 20  product_description_lenght     117604 non-null  float64
 21  product_photos_qty             117604 non-null  float64
 22  product_weight_g               117604 non-null  float64
 23  product_length_cm              117604 non-null  float64
 24  product_height_cm              117604 non-null  float64
 25  product_width_cm               117604 non-null  float64
 26  seller_zip_code_prefix         117604 non-null  float64
 27  seller_city                    117604 non-null  object
 28  seller_state                   117604 non-null  object
 29  payment_sequential             118431 non-null  float64
 30  payment_type                   118431 non-null  object
 31  payment_installments           118431 non-null  float64
 32  payment_value                  118431 non-null  float64
dtypes: datetime64[ns](6), float64(14), int64(1), object(12)
memory usage: 29.8+ MB

None

In [22]:
df_merged = pd.merge(df_merged, df_order_reviews, on='order_id', how='left')
display(df_merged.head())
display(df_merged.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,,,2018-08-18 00:00:00,2018-08-22 19:07:58

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  datetime64[ns]
 4   order_approved_at              119143 non-null  datetime64[ns]
 5   order_delivered_carrier_date   119143 non-null  datetime64[ns]
 6   order_delivered_customer_date  119143 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119143 non-null  datetime64[ns]
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  datetime64[ns]
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          118310 non-null  object
 19  product_name_lenght            118310 non-null  float64
 20  product_description_lenght     118310 non-null  float64
 21  product_photos_qty             118310 non-null  float64
 22  product_weight_g               118310 non-null  float64
 23  product_length_cm              118310 non-null  float64
 24  product_height_cm              118310 non-null  float64
 25  product_width_cm               118310 non-null  float64
 26  seller_zip_code_prefix         118310 non-null  float64
 27  seller_city                    118310 non-null  object
 28  seller_state                   118310 non-null  object
 29  payment_sequential             119140 non-null  float64
 30  payment_type                   119140 non-null  object
 31  payment_installments           119140 non-null  float64
 32  payment_value                  119140 non-null  float64
 33  review_id                      118146 non-null  object
 34  review_score                   118146 non-null  float64
 35  review_comment_title           118146 non-null  object
 36  review_comment_message         118146 non-null  object
 37  review_creation_date           118146 non-null  object
 38  review_answer_timestamp        118146 non-null  object
dtypes: datetime64[ns](6), float64(15), int64(1), object(17)
memory usage: 35.5+ MB

None

In [23]:
df_merged = pd.merge(df_merged, df_product_category_name_translation, on='product_category_name', how='left')
display(df_merged.head())
display(df_merged.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,,,2018-08-18 00:00:00,2018-08-22 19:07:58,auto

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  datetime64[ns]
 4   order_approved_at              119143 non-null  datetime64[ns]
 5   order_delivered_carrier_date   119143 non-null  datetime64[ns]
 6   order_delivered_customer_date  119143 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119143 non-null  datetime64[ns]
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  datetime64[ns]
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          118310 non-null  object
 19  product_name_lenght            118310 non-null  float64
 20  product_description_lenght     118310 non-null  float64
 21  product_photos_qty             118310 non-null  float64
 22  product_weight_g               118310 non-null  float64
 23  product_length_cm              118310 non-null  float64
 24  product_height_cm              118310 non-null  float64
 25  product_width_cm               118310 non-null  float64
 26  seller_zip_code_prefix         118310 non-null  float64
 27  seller_city                    118310 non-null  object
 28  seller_state                   118310 non-null  object
 29  payment_sequential             119140 non-null  float64
 30  payment_type                   119140 non-null  object
 31  payment_installments           119140 non-null  float64
 32  payment_value                  119140 non-null  float64
 33  review_id                      118146 non-null  object
 34  review_score                   118146 non-null  float64
 35  review_comment_title           118146 non-null  object
 36  review_comment_message         118146 non-null  object
 37  review_creation_date           118146 non-null  object
 38  review_answer_timestamp        118146 non-null  object
 39  product_category_name_english  116576 non-null  object
dtypes: datetime64[ns](6), float64(15), int64(1), object(18)
memory usage: 36.4+ MB

None

### Further Data Type Conversion and Missing Value Handling in Merged DataFrame

In [26]:
# Convert review timestamp columns to datetime
datetime_cols_reviews = ['review_creation_date', 'review_answer_timestamp']
for col in datetime_cols_reviews:
    df_merged[col] = pd.to_datetime(df_merged[col], errors='coerce') # Use 'coerce' to turn unparseable dates into NaT

# Fill missing product_category_name_english with 'unknown_category_english'
df_merged['product_category_name_english'] = df_merged['product_category_name_english'].fillna('unknown_category_english')

# For remaining numerical columns introduced by left merges (e.g., from order_items, payments, reviews),
# fill NaN values with 0 or an appropriate indicator, depending on their meaning.
# For example, order_item_id, price, freight_value, payment_sequential, payment_installments, payment_value, review_score.
# If an order has no items, the item-specific columns will be NaN. Filling with 0 makes sense if it implies 'no value'.
# Similarly for payments and reviews, if an order has no corresponding entry, it implies no payment/review data.

# Numerical columns to fill with 0 (assuming NaN means absence/zero value)
numerical_cols_to_fill = [
    'order_item_id', 'price', 'freight_value',
    'product_name_lenght', 'product_description_lenght', 'product_photos_qty',
    'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm',
    'seller_zip_code_prefix', 'payment_sequential', 'payment_installments', 'payment_value',
    'review_score'
]

for col in numerical_cols_to_fill:
    df_merged[col] = df_merged[col].fillna(0)

# Fill remaining object type columns with 'unknown' or empty string where appropriate
object_cols_to_fill = [
    'product_id', 'seller_id', 'seller_city', 'seller_state',
    'payment_type', 'review_id', 'review_comment_title', 'review_comment_message'
]

for col in object_cols_to_fill:
    if col in df_merged.columns:
        df_merged[col] = df_merged[col].fillna('unknown')

# Handle remaining specific missing values after merges and initial filling
# Fill missing 'shipping_limit_date' with 'order_purchase_timestamp'
df_merged['shipping_limit_date'] = df_merged['shipping_limit_date'].fillna(df_merged['order_purchase_timestamp'])

# Fill missing 'product_category_name' with 'unknown'
df_merged['product_category_name'] = df_merged['product_category_name'].fillna('unknown')

# Fill remaining NaT values in review timestamp columns with 'order_purchase_timestamp'
df_merged['review_creation_date'] = df_merged['review_creation_date'].fillna(df_merged['order_purchase_timestamp'])
df_merged['review_answer_timestamp'] = df_merged['review_answer_timestamp'].fillna(df_merged['order_purchase_timestamp'])

display(df_merged.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  datetime64[ns]
 4   order_approved_at              119143 non-null  datetime64[ns]
 5   order_delivered_carrier_date   119143 non-null  datetime64[ns]
 6   order_delivered_customer_date  119143 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119143 non-null  datetime64[ns]
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  119143 non-null  float64
 13  product_id                     119143 non-null  object
 14  seller_id                      119143 non-null  object
 15  shipping_limit_date            119143 non-null  datetime64[ns]
 16  price                          119143 non-null  float64
 17  freight_value                  119143 non-null  float64
 18  product_category_name          119143 non-null  object
 19  product_name_lenght            119143 non-null  float64
 20  product_description_lenght     119143 non-null  float64
 21  product_photos_qty             119143 non-null  float64
 22  product_weight_g               119143 non-null  float64
 23  product_length_cm              119143 non-null  float64
 24  product_height_cm              119143 non-null  float64
 25  product_width_cm               119143 non-null  float64
 26  seller_zip_code_prefix         119143 non-null  float64
 27  seller_city                    119143 non-null  object
 28  seller_state                   119143 non-null  object
 29  payment_sequential             119143 non-null  float64
 30  payment_type                   119143 non-null  object
 31  payment_installments           119143 non-null  float64
 32  payment_value                  119143 non-null  float64
 33  review_id                      119143 non-null  object
 34  review_score                   119143 non-null  float64
 35  review_comment_title           119143 non-null  object
 36  review_comment_message         119143 non-null  object
 37  review_creation_date           119143 non-null  datetime64[ns]
 38  review_answer_timestamp        119143 non-null  datetime64[ns]
 39  product_category_name_english  119143 non-null  object
dtypes: datetime64[ns](8), float64(15), int64(1), object(16)
memory usage: 36.4+ MB

None

### Define Product Attributes

In [27]:
# 1. Merge df_products with df_product_category_name_translation
# This gives us product_id, product_category_name, and product_category_name_english
df_product_catalog_temp = pd.merge(df_products, df_product_category_name_translation,
                                   on='product_category_name', how='left')

# Fill any remaining missing product_category_name_english (e.g., if 'unknown' category wasn't translated)
df_product_catalog_temp['product_category_name_english'] = df_product_catalog_temp['product_category_name_english'].fillna('unknown_category_english')

# 2. Calculate average price per product_id from df_order_items
# This ensures a single price entry per product if a product appears in multiple order items with slightly varying prices
df_product_prices = df_order_items.groupby('product_id')['price'].mean().reset_index()
df_product_prices.rename(columns={'price': 'avg_price'}, inplace=True) # Rename for clarity before final merge

# 3. Merge the product details with the calculated average prices
df_final_products = pd.merge(df_product_catalog_temp, df_product_prices,
                             on='product_id', how='left')

# 4. Select and rename columns to match the requested attributes
# Use 'product_category_name_english' for both 'name' (as a proxy) and 'category'
df_products_attributes = df_final_products[[
    'product_id',
    'product_category_name_english',
    'avg_price'
]].copy()

df_products_attributes.rename(columns={
    'product_id': '_id',
    'product_category_name_english': 'category',
    'avg_price': 'price'
}, inplace=True)

# Add 'name' column using 'category' as a proxy
df_products_attributes['name'] = df_products_attributes['category']

# Reorder columns to desired order: _id, name, category, price
df_products_attributes = df_products_attributes[['_id', 'name', 'category', 'price']]

# 5. Handle missing 'price' values for products that never appeared in an order item
df_products_attributes['price'] = df_products_attributes['price'].fillna(0)

display(df_products_attributes.head())
display(df_products_attributes.info())

                                _id            name        category   price
0  1e9e8ef04dbcff4541ed26657ea517e5       perfumery       perfumery   10.91
1  3aa071139cb16b67ca9e5dea641aaa2f             art             art  248.00
2  96bd76ec8810374ed1b65e291975717f  sports_leisure  sports_leisure   79.80
3  cef67bcfe19066a932b7673e239eb23d            baby            baby  112.30
4  9dc1a7de274444849c219cff195d0b71      housewares      housewares   37.90

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   _id       32951 non-null  object
 1   name      32951 non-null  object
 2   category  32951 non-null  object
 3   price     32951 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.0+ MB

None

### Insert Product Attributes into MongoDB

In [28]:
products_collection = db['products']

# Convert DataFrame to a list of dictionaries (JSON documents)
product_data = df_products_attributes.to_dict(orient='records')

# Insert the documents into the 'products' collection
# Using insert_many for efficiency
result = products_collection.insert_many(product_data)

print(f"Inserted {len(result.inserted_ids)} product documents into the 'products' collection.")

# Verify by counting documents in the collection
print(f"Total documents in 'products' collection: {products_collection.count_documents({})}")

Inserted 32951 product documents into the 'products' collection.
Total documents in 'products' collection: 32951

In [18]:
df_merged = pd.merge(df_merged, df_order_items, on='order_id', how='left')
display(df_merged.head())
display(df_merged.info())

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  object
 1   customer_id                    113425 non-null  object
 2   order_status                   113425 non-null  object
 3   order_purchase_timestamp       113425 non-null  datetime64[ns]
 4   order_approved_at              113425 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113425 non-null  datetime64[ns]
 6   order_delivered_customer_date  113425 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113425 non-null  datetime64[ns]
 8   customer_unique_id             113425 non-null  object
 9   customer_zip_code_prefix       113425 non-null  int64
 10  customer_city                  113425 non-null  object
 11  customer_state                 113425 non-null  object
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  object
 14  seller_id                      112650 non-null  object
 15  shipping_limit_date            112650 non-null  datetime64[ns]
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
dtypes: datetime64[ns](6), float64(3), int64(1), object(8)
memory usage: 15.6+ MB

None

In [17]:
from pymongo import MongoClient
from pymongo.server_api import ServerApi

# La contraseña 'Colombia2010$' se usa directamente sin los corchetes angulares.
# Asegúrate de que esta sea tu contraseña real.
uri = "mongodb+srv://romergi01:Colombia2010$@clusterger01.m5h1dhu.mongodb.net/?appName=ClusterGer01"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [25]:
db_name = "EcommifyDB"
db = client[db_name]

# To confirm the database is created, we can insert a dummy document into a collection
# MongoDB creates the database and collection implicitly on the first write operation.
collection_name = "test_collection"
db[collection_name].insert_one({"message": "Database created successfully!"})

print(f"Database '{db_name}' and collection '{collection_name}' created/accessed successfully.")

# Optional: Verify the database exists by listing database names
print("List of databases:", client.list_database_names())

Database 'EcommifyDB' and collection 'test_collection' created/accessed successfully.
List of databases: ['EcommifyDB', 'sample_mflix', 'admin', 'local']

### Apply Computed Pattern for Pre-calculated Metrics

In [31]:
# 1. Calculate total_units_sold for each product
df_total_units_sold = df_merged.groupby('product_id')['order_item_id'].sum().reset_index()
df_total_units_sold.rename(columns={'order_item_id': 'total_units_sold', 'product_id': '_id'}, inplace=True)

# 2. Calculate average_rating for each product
df_average_rating = df_merged.groupby('product_id')['review_score'].mean().reset_index()
df_average_rating.rename(columns={'review_score': 'average_rating', 'product_id': '_id'}, inplace=True)

# 3. Merge these pre-calculated metrics into df_products_with_specs
df_products_with_metrics = pd.merge(df_products_with_specs, df_total_units_sold, on='_id', how='left')
df_products_with_metrics = pd.merge(df_products_with_metrics, df_average_rating, on='_id', how='left')

# Fill NaN values for products with no sales or reviews
df_products_with_metrics['total_units_sold'] = df_products_with_metrics['total_units_sold'].fillna(0)
df_products_with_metrics['average_rating'] = df_products_with_metrics['average_rating'].fillna(0)

display(df_products_with_metrics.head())
display(df_products_with_metrics.info())

,_id,name,category,price,specifications,total_units_sold,average_rating
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,perfumery,10.91,"{'product_name_lenght': 40.0, 'product_descrip...",1.0,5.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,art,248.00,"{'product_name_lenght': 44.0, 'product_descrip...",1.0,5.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,sports_leisure,79.80,"{'product_name_lenght': 46.0, 'product_descrip...",1.0,5.0
3,cef67bcfe19066a932b7673e239eb23d,baby,baby,112.30,"{'product_name_lenght': 27.0, 'product_descrip...",1.0,1.0
4,9dc1a7de274444849c219cff195d0b71,housewares,housewares,37.90,"{'product_name_lenght': 37.0, 'product_descrip...",1.0,5.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               32951 non-null  object
 1   name              32951 non-null  object
 2   category          32951 non-null  object
 3   price             32951 non-null  float64
 4   specifications    32951 non-null  object
 5   total_units_sold  32951 non-null  float64
 6   average_rating    32951 non-null  float64
dtypes: float64(3), object(4)
memory usage: 1.8+ MB

None

### Update Product Collection in MongoDB with Computed Metrics

In [32]:
# Get the 'products' collection
products_collection = db['products']

# Iterate through the DataFrame and update each document in MongoDB
updated_count_metrics = 0
for index, row in df_products_with_metrics.iterrows():
    product_id = row['_id']
    total_units_sold = row['total_units_sold']
    average_rating = row['average_rating']

    # Update the document in MongoDB with the new metrics
    result = products_collection.update_one(
        {'_id': product_id},
        {'$set': {
            'metrics.total_units_sold': total_units_sold,
            'metrics.average_rating': average_rating
        }}
    )
    if result.modified_count > 0:
        updated_count_metrics += 1

print(f"Updated {updated_count_metrics} product documents with computed metrics in the 'products' collection.")

# Verify a sample document to check the update
print("\nSample document after metrics update:")
sample_product_metrics = products_collection.find_one({'metrics.total_units_sold': {'$exists': True}})
if sample_product_metrics:
    display(sample_product_metrics)
else:
    print("No product found with metrics.")

Updated 32951 product documents with computed metrics in the 'products' collection.

Sample document after metrics update:

{'_id': '1e9e8ef04dbcff4541ed26657ea517e5',
 'name': 'perfumery',
 'category': 'perfumery',
 'price': 10.91,
 'specifications': {'product_name_lenght': 40.0,
  'product_description_lenght': 287.0,
  'product_photos_qty': 1.0,
  'product_weight_g': 225.0,
  'product_length_cm': 16.0,
  'product_height_cm': 10.0,
  'product_width_cm': 14.0},
 'metrics': {'average_rating': 5.0, 'total_units_sold': 1.0}}

### Prepare and Insert Sample Product Collection

### Exploring Data with MongoDB Queries and Aggregation Pipelines

We will now use `pymongo` to perform various queries and aggregation pipelines on our `products` and `reviews` collections. These examples demonstrate how to retrieve specific data, filter, sort, and calculate aggregated metrics, leveraging the structured and embedded document design we've implemented.

#### Query 1: Find Products by Category, Sorted by Price

This query demonstrates how to find all products belonging to a specific category and then sort them by their price in ascending order. We'll project only the relevant fields (`_id`, `name`, `category`, `price`).

In [36]:
# Get the 'products' collection
products_collection = db['products']

# Define the category to search for
category_to_search = 'health_beauty'

# Perform the query
print(f"Products in category '{category_to_search}', sorted by price (top 5):\n")
for product in products_collection.find(
    {'category': category_to_search},
    {'_id': 1, 'name': 1, 'category': 1, 'price': 1}
).sort('price', 1).limit(5):
    display(product)

Products in category 'health_beauty', sorted by price (top 5):

{'_id': '270516a3f41dc035aa87d220228f844c',
 'name': 'health_beauty',
 'category': 'health_beauty',
 'price': 1.2}

{'_id': '05b515fdc76e888aada3c6d66c201dff',
 'name': 'health_beauty',
 'category': 'health_beauty',
 'price': 1.2}

{'_id': '46fce52cef5caa7cc225a5531c946c8b',
 'name': 'health_beauty',
 'category': 'health_beauty',
 'price': 2.2}

{'_id': 'da86f3242cb55a55dd9cd7b19d951685',
 'name': 'health_beauty',
 'category': 'health_beauty',
 'price': 4.5}

{'_id': '99b5175198369d12de8feee13dafac16',
 'name': 'health_beauty',
 'category': 'health_beauty',
 'price': 5.0}

#### Query 2: Find Products with High Average Ratings (e.g., >= 4.5)

This query uses the pre-calculated `metrics.average_rating` field to find products that have received high average scores, sorted in descending order of rating.

In [37]:
print("Products with an average rating of 4.5 or higher (top 5):\n")
for product in products_collection.find(
    {'metrics.average_rating': {'$gte': 4.5}},
    {'_id': 1, 'name': 1, 'category': 1, 'metrics.average_rating': 1, 'price': 1}
).sort('metrics.average_rating', -1).limit(5):
    display(product)

Products with an average rating of 4.5 or higher (top 5):

{'_id': '9dc1a7de274444849c219cff195d0b71',
 'name': 'housewares',
 'category': 'housewares',
 'price': 37.9,
 'metrics': {'average_rating': 5.0}}

{'_id': '41d3672d4792049fa1779bb35283ed13',
 'name': 'musical_instruments',
 'category': 'musical_instruments',
 'price': 45.87,
 'metrics': {'average_rating': 5.0}}

{'_id': '3aa071139cb16b67ca9e5dea641aaa2f',
 'name': 'art',
 'category': 'art',
 'price': 248.0,
 'metrics': {'average_rating': 5.0}}

{'_id': '1e9e8ef04dbcff4541ed26657ea517e5',
 'name': 'perfumery',
 'category': 'perfumery',
 'price': 10.91,
 'metrics': {'average_rating': 5.0}}

{'_id': '96bd76ec8810374ed1b65e291975717f',
 'name': 'sports_leisure',
 'category': 'sports_leisure',
 'price': 79.8,
 'metrics': {'average_rating': 5.0}}

#### Aggregation Pipeline 1: Top 5 Products by Total Units Sold

This pipeline retrieves the top 5 products based on their `metrics.total_units_sold`. It demonstrates accessing nested fields in aggregation.

In [38]:
print("Top 5 products by total units sold:\n")
pipeline_top_sold = [
    {'$sort': {'metrics.total_units_sold': -1}},
    {'$limit': 5},
    {'$project': {
        '_id': 1,
        'name': 1,
        'category': 1,
        'total_units_sold': '$metrics.total_units_sold'
    }}
]

for doc in products_collection.aggregate(pipeline_top_sold):
    display(doc)

Top 5 products by total units sold:

{'_id': '422879e10f46682990de24d770e7f83d',
 'name': 'garden_tools',
 'category': 'garden_tools',
 'total_units_sold': 826.0}

{'_id': 'aca2eb7d00ea1a7b8ebd4e68314663af',
 'name': 'furniture_decor',
 'category': 'furniture_decor',
 'total_units_sold': 650.0}

{'_id': '99a4788cb24856965c36a24e339b6058',
 'name': 'bed_bath_table',
 'category': 'bed_bath_table',
 'total_units_sold': 588.0}

{'_id': '368c6c730842d78016ad823897a372db',
 'name': 'garden_tools',
 'category': 'garden_tools',
 'total_units_sold': 564.0}

{'_id': '53759a2ecddad2bb87a079a1f1519f73',
 'name': 'garden_tools',
 'category': 'garden_tools',
 'total_units_sold': 563.0}

#### Aggregation Pipeline 2: Average Review Score per Product Category

This pipeline calculates the average review score for each product category. It groups documents by `category`, computes the average `metrics.average_rating`, and then sorts the results.

In [39]:
print("Average review score per product category (top 5 categories):\n")
pipeline_avg_rating_category = [
    {'$match': {'category': {'$ne': 'unknown_category_english'}}},
    {'$group': {
        '_id': '$category',
        'average_review_score': {'$avg': '$metrics.average_rating'}
    }},
    {'$sort': {'average_review_score': -1}},
    {'$limit': 5}
]

for doc in products_collection.aggregate(pipeline_avg_rating_category):
    display(doc)

Average review score per product category (top 5 categories):

{'_id': 'cds_dvds_musicals', 'average_review_score': 4.642857142857143}

{'_id': 'home_comfort_2', 'average_review_score': 4.607407407407408}

{'_id': 'books_technical', 'average_review_score': 4.4301465755521345}

{'_id': 'fashion_sport', 'average_review_score': 4.383333333333333}

{'_id': 'arts_and_craftmanship', 'average_review_score': 4.3578947368421055}

#### Query 3: Retrieve All Reviews for a Specific Product

This query demonstrates how to find all reviews associated with a particular `product_id` from the `reviews` collection. This highlights the external reference pattern.

In [40]:
# Get the 'reviews' collection
reviews_collection = db['reviews']

# Example product_id (you can get this from previous product queries)
example_product_id = '1e9e8ef04dbcff4541ed26657ea517e5'

print(f"All reviews for product ID '{example_product_id}' (top 3):\n")
for review in reviews_collection.find(
    {'product_id': example_product_id}
).limit(3):
    display(review)

All reviews for product ID '1e9e8ef04dbcff4541ed26657ea517e5' (top 3):

{'_id': 'd71da8fd8c6e3adef26be965f065b8a1',
 'order_id': 'e17e4f88e31525f7deef66779844ddce',
 'product_id': '1e9e8ef04dbcff4541ed26657ea517e5',
 'customer_id': 'f8a3e963a310aa58b60a5b1fed5bceb5',
 'review_score': 5.0,
 'review_comment_title': 'Vale a pena ',
 'review_comment_message': 'Super adooorei o delineador ele é bem preto e eu smp usei o da Mac e serio o da belle angel me surpreendeu pq eu achei que por ser barato iria ser ruim mas NAO é ... o unico problema é q ele é pequeno',
 'review_creation_date': datetime.datetime(2018, 4, 28, 0, 0),
 'review_answer_timestamp': datetime.datetime(2018, 5, 4, 0, 55, 2)}

### Create and Insert 'reviews' Collection with External References

In [35]:
# Select relevant columns for the reviews collection
df_reviews_collection = df_merged[[
    'review_id',
    'order_id',
    'product_id',
    'customer_id',
    'review_score',
    'review_comment_title',
    'review_comment_message',
    'review_creation_date',
    'review_answer_timestamp'
]].drop_duplicates(subset=['review_id']).copy()

# Rename 'review_id' to '_id' for MongoDB primary key
df_reviews_collection.rename(columns={'review_id': '_id'}, inplace=True)

# Convert to a list of dictionaries for insertion
reviews_data = df_reviews_collection.to_dict(orient='records')

# Get or create the 'reviews' collection
reviews_collection = db['reviews']

# Clear existing data in the collection to ensure a fresh insert
reviews_collection.delete_many({})

# Insert the review documents
if reviews_data:
    insert_result_reviews = reviews_collection.insert_many(reviews_data)
    print(f"Inserted {len(insert_result_reviews.inserted_ids)} review documents into the 'reviews' collection.")
    print(f"Total documents in 'reviews' collection: {reviews_collection.count_documents({})}.")

    # Verify a sample document from the new collection
    print("\nSample document from 'reviews' collection:")
    sample_review_doc = reviews_collection.find_one()
    if sample_review_doc:
        display(sample_review_doc)
    else:
        print("No documents found in 'reviews' collection.")
else:
    print("No review data to insert.")

Inserted 98411 review documents into the 'reviews' collection.
Total documents in 'reviews' collection: 98411.

Sample document from 'reviews' collection:

{'_id': 'a54f0611adc9ed256b57ede6b6eb5114',
 'order_id': 'e481f51cbdc54678b7cc49136f2d6af7',
 'product_id': '87285b34884572647811a353c7ac498a',
 'customer_id': '9ef432eb6251297304e76186b10a928d',
 'review_score': 4.0,
 'review_comment_title': '',
 'review_comment_message': 'Não testei o produto ainda, mas ele veio correto e em boas condições. Apenas a caixa que veio bem amassada e danificada, o que ficará chato, pois se trata de um presente.',
 'review_creation_date': datetime.datetime(2017, 10, 11, 0, 0),
 'review_answer_timestamp': datetime.datetime(2017, 10, 12, 3, 43, 48)}

### Create Sample from MongoDB 'products' Collection

In [34]:
# Get the 'products' collection
products_collection = db['products']

# Get or create the 'products_sample_from_db' collection
products_sample_from_db_collection = db['products_sample_from_db']

# Clear previous data in the sample collection
products_sample_from_db_collection.delete_many({})

# Retrieve the first 1000 documents from the 'products' collection
sample_documents = list(products_collection.find().limit(1000))

# Insert the retrieved sample documents into the new collection
if sample_documents:
    insert_result_db = products_sample_from_db_collection.insert_many(sample_documents)
    print(f"Inserted {len(insert_result_db.inserted_ids)} sample product documents into the 'products_sample_from_db' collection.")
    print(f"Total documents in 'products_sample_from_db' collection: {products_sample_from_db_collection.count_documents({})}.")

    # Verify a sample document from the new collection
    print("\nSample document from 'products_sample_from_db' collection:")
    sample_doc_from_db = products_sample_from_db_collection.find_one()
    if sample_doc_from_db:
        display(sample_doc_from_db)
    else:
        print("No documents found in 'products_sample_from_db' collection.")
else:
    print("No documents found in the original 'products' collection to sample.")

Inserted 1000 sample product documents into the 'products_sample_from_db' collection.
Total documents in 'products_sample_from_db' collection: 1000.

Sample document from 'products_sample_from_db' collection:

{'_id': '1e9e8ef04dbcff4541ed26657ea517e5',
 'name': 'perfumery',
 'category': 'perfumery',
 'price': 10.91,
 'specifications': {'product_name_lenght': 40.0,
  'product_description_lenght': 287.0,
  'product_photos_qty': 1.0,
  'product_weight_g': 225.0,
  'product_length_cm': 16.0,
  'product_height_cm': 10.0,
  'product_width_cm': 14.0},
 'metrics': {'average_rating': 5.0, 'total_units_sold': 1.0}}

In [33]:
# Take the first 1000 documents from df_products_with_metrics as a sample
df_sample_products = df_products_with_metrics.head(1000).copy()

# Convert the sample DataFrame to a list of dictionaries
sample_product_data = df_sample_products.to_dict(orient='records')

# Get or create the 'sample_products' collection
sample_products_collection = db['sample_products']

# Clear previous data in the sample collection if any, to ensure a clean insert for demonstration
sample_products_collection.delete_many({})

# Insert the sample documents
insert_result = sample_products_collection.insert_many(sample_product_data)

print(f"Inserted {len(insert_result.inserted_ids)} sample product documents into the 'sample_products' collection.")
print(f"Total documents in 'sample_products' collection: {sample_products_collection.count_documents({})}.")

# Verify a sample document from the new collection
print("\nSample document from 'sample_products' collection:")
sample_doc = sample_products_collection.find_one()
if sample_doc:
    display(sample_doc)
else:
    print("No documents found in 'sample_products' collection.")

Inserted 1000 sample product documents into the 'sample_products' collection.
Total documents in 'sample_products' collection: 1000.

Sample document from 'sample_products' collection:

{'_id': '1e9e8ef04dbcff4541ed26657ea517e5',
 'name': 'perfumery',
 'category': 'perfumery',
 'price': 10.91,
 'specifications': {'product_name_lenght': 40.0,
  'product_description_lenght': 287.0,
  'product_photos_qty': 1.0,
  'product_weight_g': 225.0,
  'product_length_cm': 16.0,
  'product_height_cm': 10.0,
  'product_width_cm': 14.0},
 'total_units_sold': 1.0,
 'average_rating': 5.0}

### Design Flexible 'specifications' Subdocument

In [29]:
# 1. Select the relevant product specification columns from df_products
specification_cols = [
    'product_id',
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]
df_product_specs = df_products[specification_cols].copy()

# 2. Convert each row of specifications into a dictionary, grouped by product_id
def create_specs_dict(row):
    # Exclude 'product_id' from the specifications dictionary
    return {col: row[col] for col in specification_cols if col != 'product_id'}

df_product_specs['specifications'] = df_product_specs.apply(create_specs_dict, axis=1)

# 3. Create a DataFrame with just product_id and the new 'specifications' column
df_product_specs_final = df_product_specs[['product_id', 'specifications']].copy()
df_product_specs_final.rename(columns={'product_id': '_id'}, inplace=True)

# 4. Merge this back with df_products_attributes
# This will add the 'specifications' subdocument to our product catalog
df_products_with_specs = pd.merge(df_products_attributes, df_product_specs_final,
                                  on='_id', how='left')

display(df_products_with_specs.head())
display(df_products_with_specs.info())

,_id,name,category,price,specifications
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,perfumery,10.91,"{'product_name_lenght': 40.0, 'product_descrip..."
1,3aa071139cb16b67ca9e5dea641aaa2f,art,art,248.00,"{'product_name_lenght': 44.0, 'product_descrip..."
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,sports_leisure,79.80,"{'product_name_lenght': 46.0, 'product_descrip..."
3,cef67bcfe19066a932b7673e239eb23d,baby,baby,112.30,"{'product_name_lenght': 27.0, 'product_descrip..."
4,9dc1a7de274444849c219cff195d0b71,housewares,housewares,37.90,"{'product_name_lenght': 37.0, 'product_descrip..."

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   _id             32951 non-null  object
 1   name            32951 non-null  object
 2   category        32951 non-null  object
 3   price           32951 non-null  float64
 4   specifications  32951 non-null  object
dtypes: float64(1), object(4)
memory usage: 1.3+ MB

None

### Update Product Collection in MongoDB with Specifications

In [30]:
# Get the 'products' collection
products_collection = db['products']

# Iterate through the DataFrame and update each document in MongoDB
updated_count = 0
for index, row in df_products_with_specs.iterrows():
    product_id = row['_id']
    specifications = row['specifications']

    # Update the document in MongoDB
    result = products_collection.update_one(
        {'_id': product_id},
        {'$set': {'specifications': specifications}}
    )
    if result.modified_count > 0:
        updated_count += 1

print(f"Updated {updated_count} product documents with specifications in the 'products' collection.")

# Verify a sample document to check the update
print("\nSample document after update:")
# Find one document that has specifications and display it
sample_product = products_collection.find_one({'specifications': {'$exists': True}})
if sample_product:
    display(sample_product)
else:
    print("No product found with specifications.")

Updated 32951 product documents with specifications in the 'products' collection.

Sample document after update:

{'_id': '1e9e8ef04dbcff4541ed26657ea517e5',
 'name': 'perfumery',
 'category': 'perfumery',
 'price': 10.91,
 'specifications': {'product_name_lenght': 40.0,
  'product_description_lenght': 287.0,
  'product_photos_qty': 1.0,
  'product_weight_g': 225.0,
  'product_length_cm': 16.0,
  'product_height_cm': 10.0,
  'product_width_cm': 14.0}}